version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket && cp -r index.html assets bucket
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./bucket
          to: 's3://templo-de-la-santa-cruz-queretaro-landing-page'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: ./bucket
          to: 's3://templo-de-la-santa-cruz-queretaro-landing-page'
workflows:
  s3-example:
    jobs:
      - build
